### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Rastopyr** [Rastopyr/mix-newer#2]
## Motivation for upgrade

In current point exist many good solutions for scaffold applications. Eg:

* [phoenix](https://github.com/phoenixframework/phoenix/tree/20e2826587b25227e107a83fbb56ce7f4d0c731f/lib/mix/tasks)
* [ruby on rails](https://github.com/rails/rails/tree/a8b996a0eee9aae455c5f82fac0baf24edb3a9c1/railties/lib/rails/generators)
* [ember-cli](https://github.com/ember-cli/ember-cli/tree/master/blueprints)

But elixir ecosystem doesn't have abstarction for scaffold projects(not to mention phoenix). So this is reason, upgrade and support this project.

 ## Improvement proposals

- [ ] Cover of tests
- [x] Code style with [Dogma](https://github.com/lpil/dogma)
- [ ] Refactor codebase
- [ ] API for mix `newer.gen`
